import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "../components/user components/Home/Header";
import Footer from "../components/user components/Footer";
import ReduxProvider from "@/redux/ReduxProvider";
import { getMe } from "@/api_call/serverApi";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // Must specify weights for non-variable fonts
  display: "swap",
  variable: "--font-poppins", // Optional: Creates a CSS variable
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ishop",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await getMe()
  return (
    <html lang="en" className={`${poppins.className} ${poppins.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
      >
        <ReduxProvider>
        <Header user={user} />
        {children}
        <Footer/>
        </ReduxProvider>
      </body>
    </html>
  )
}
